# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 972610c6d7314bae0be1635271db2849eecb1882e1c820da30b2fefa26cd233d7d98019244db72df89f4604edc330feeafc6fbed6a36c7067952302e241d5515

test:
  secret_key_base: 8d65871c01254a127e8c718983672ce30e86bdc370bceae0046d8b293dfab5d9b6a9b94f62232e42b87c2eca3008bacb8dddb46d2c973f60c5591de1d3fac589

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
